name = "indexer"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

services = [
  { binding = "Access", service = "access" },
  { binding = "Edges", service = "edges" }
]

[[ d1_databases ]]
binding = "COLLECTIONS" # i.e. available in your Worker on env.DB
database_name = "collections"
database_id = "6b8d7d24-75a2-493f-93d7-149927d340a9"
migrations_dir = "migrations"

[[queues.producers]]
 queue = "blockchain-activity"
 binding = "BLOCKCHAIN_ACTIVITY"
 
[[queues.consumers]]
queue = "blockchain-activity"
max_batch_size = 1 # optional: defaults to 10
max_batch_timeout = 5 # optional: defaults to 5 seconds

[vars]

[dev]
port = 8990
local_protocol = "http"

[env.dev]
services = [
  { binding = "Access", service = "access-dev" },
  { binding = "Edges", service = "edges-dev" }
]
d1_databases = [
  { binding = "COLLECTIONS", database_name = "collections-dev", database_id = "6b8d7d24-75a2-493f-93d7-149927d340a9", migrations_dir = "migrations" }
]

[env.dev.vars]

[env.next]
services = [
  { binding = "Access", service = "access-next" },
  { binding = "Edges", service = "edges-next" }
]
d1_databases = [
  { binding = "COLLECTIONS", database_name = "collections-next", database_id = "63ee76ae-6440-43a9-9183-13b7515d2752", migrations_dir = "migrations" }
]

[env.next.vars]

[env.current]
services = [
  { binding = "Access", service = "access-current" },
  { binding = "Edges", service = "edges-current" }
]
d1_databases = [
  { binding = "COLLECTIONS", database_name = "collections-current", database_id = "e3caaae6-d327-4a0b-92b0-a35b7f9ac819", migrations_dir = "migrations" }
]

[env.current.vars]
