# cfw/icons/wrangler.toml

name = "icons"
main = "src/index.ts"
compatibility_date = "2022-10-05"

# We'll access these services through their external names.
workers_dev = false

# Secrets are set via the dashboard, or using the wrangler CLI:
# $ wrangler secret put <KEY> [--env]
#
# Required secrets:
# - CLOUDFLARE_ACCOUNT_ID: the CF account ID of the uploaded image owner
# - CLOUDFLARE_IMAGES_KEY: an API token with Images permissions
[dev]
port = 8989
local_protocol = "http"

[env.dev]
routes = [
  { pattern = "icons-dev.kubelt.com", custom_domain = true, zone_name = "kubelt.com" }
]

[env.dev.vars]
# The duration in seconds that returned upload URL is good for.
# - minimum: 2 minutes (120)
# - maximum: 6 hours (21600)
UPLOAD_WINDOW_SECONDS = 200

[env.next]
routes = [
  { pattern = "icons-next.kubelt.com", custom_domain = true, zone_name = "kubelt.com" }
]

[env.next.vars]
# The duration in seconds that returned upload URL is good for.
# - minimum: 2 minutes (120)
# - maximum: 6 hours (21600)
UPLOAD_WINDOW_SECONDS = 200

[env.current]
routes = [
  { pattern = "icons.kubelt.com", custom_domain = true, zone_name = "kubelt.com" }
]

[env.current.vars]
# The duration in seconds that returned upload URL is good for.
# - minimum: 2 minutes (120)
# - maximum: 6 hours (21600)
UPLOAD_WINDOW_SECONDS = 200
