# Meta Data for SEO

## Homepage
title = "Kubelt"
titleSeparator = "-"
titleAddition = "Decentralized content management"
description = "Decentralized content management"

## Social
githubUrl = 'https://github.com/kubelt'
githubIcon = 'images/Social-link4.svg'

twitterUrl = 'https://twitter.com/kubelt'
twitterIcon = 'images/Social-link3.svg'

discordUrl = 'https://discord.gg/UgwAsJf6C5'
discordIcon = 'images/discord-icon.svg'

## Documentation
docsVersion = "next"

## Open Graph
images = ["images/sociallogo.png"]
ogLocale = "en_US"
domainTLD = "kubelt.com"
titleHome = "Kubelt - Decentralized content management"

## Twitter Cards
twitterSite = "@kubelt"
twitterCreator = "@kubelt"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Kubelt"
schemaAuthor = "Kubelt"
schemaAuthorTwitter = "https://twitter.com/kubelt"
schemaAuthorLinkedIn = "https://www.linkedin.com/company/kubelt/"
schemaAuthorGitHub = "https://github.com/kubelt"
schemaLocale = "en-US"
schemaLogo = "images/sociallogo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/kubelt"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/kubelt"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Navbar
navbarIcon = "images/Asset-4.svg"

navbarHiringUrl = "https://kubelt.notion.site/Jobs-4c1b8408d2244797924e53c9eae65f43"
navbarHiringCopy = "Weâ€™re hiring"

# Access
accessUrl = "https://omq1ez0wxhd.typeform.com/to/IXfcN3Xf"
accessCopy = "Get Access"

# Whitepaper
whitepaperUrl = "https://github.com/kubelt/whitepaper/blob/main/kubelt_whitepaper.pdf"

# Footer
footer = "Powered by Hugo and Kubelt"
footerIcon = "images/Asset-4.svg"
footerCopy = "Decentralized content management, content delivery and content applications."

# Feed
copyrightHolder = "Kubelt, Inc."

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/kubelt"
docsRepoBranch = "main"
docsRepoSubPath = ""
editPage = false
lastMod = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = true
  multilingualMode = false
  docsVersioning = true
  fullWidth = false

[menu]
  [menu.section]
    auto = true
    collapsibleSidebar = false
