# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

main = "./build/index.js"

name = "passport"

workers_dev = false

# Services binding for local development
services = [
  { binding = "Account", service = "account" },
  { binding = "Access", service = "access" },
  { binding = "Address", service = "address" },
  { binding = "Galaxy", service = "galaxy" },
  { binding = "Starbase", service = "starbase" },
  { binding = "Images", service = "images" },
]

[site]
bucket = "./public"

[build]
command = "yarn build -- --sourcemap"

[dev]
port = 9696
local_protocol = "http"

[vars]
THREEID_APP_URL = "http://localhost:9797"
CONSOLE_APP_URL = "http://localhost:9898"
PASSPORT_REDIRECT_URL = "http://localhost:9696/authenticate/token"
COOKIE_DOMAIN = "localhost"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://localhost:9696/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://localhost:9696/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "http://localhost:9696/authenticate/twitter/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"

[env.dev]
routes = [
  { pattern = "passport-dev.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-dev" },
  { binding = "Access", service = "access-dev" },
  { binding = "Address", service = "address-dev" },
  { binding = "Galaxy", service = "galaxy-dev" },
  { binding = "Starbase", service = "starbase-dev" },
  { binding = "Images", service = "images-dev" },
]

[env.dev.vars]
THREEID_APP_URL = "https://my-dev.threeid.xyz"
CONSOLE_APP_URL = "https://console-dev.threid.xyz"
PASSPORT_REDIRECT_URL = "https://passport-dev.threeid.xyz/authenticate/token"
COOKIE_DOMAIN = "threeid.xyz"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://passport-dev.threeid.xyz/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://passport-dev.threeid.xyz/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport-dev.threeid.xyz/authenticate/twitter/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-NHNH4KRWC3"

[env.next]
routes = [
  { pattern = "passport-next.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-next" },
  { binding = "Access", service = "access-next" },
  { binding = "Address", service = "address-next" },
  { binding = "Galaxy", service = "galaxy-next" },
  { binding = "Starbase", service = "starbase-next" },
  { binding = "Images", service = "images-next" },
]

[env.next.vars]
THREEID_APP_URL = "https://my-next.threeid.xyz"
CONSOLE_APP_URL = "https://console-next.threid.xyz"
PASSPORT_REDIRECT_URL = "https://passport-next.threeid.xyz/authenticate/token"
COOKIE_DOMAIN = "threeid.xyz"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://passport-next.threeid.xyz/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://passport-next.threeid.xyz/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport-next.threeid.xyz/authenticate/twitter/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-X7ZN16M4NB"

[env.next.build]
command = "yarn build"

[env.current]
routes = [
  { pattern = "passport.threeid.xyz", custom_domain = true, zone_name = "threeid.xyz" },
]
services = [
  { binding = "Account", service = "account-current" },
  { binding = "Access", service = "access-current" },
  { binding = "Address", service = "address-current" },
  { binding = "Galaxy", service = "galaxy-current" },
  { binding = "Starbase", service = "starbase-current" },
  { binding = "Images", service = "images-current" },
]

[env.current.vars]
THREEID_APP_URL = "https://my.threeid.xyz"
CONSOLE_APP_URL = "https://console.threid.xyz"
PASSPORT_REDIRECT_URL = "https://passport.threeid.xyz/authenticate/token"
COOKIE_DOMAIN = "threeid.xyz"
INTERNAL_GOOGLE_OAUTH_CALLBACK_URL = "http://passport.threeid.xyz/authenticate/google/callback"
INTERNAL_GITHUB_OAUTH_CALLBACK_URL = "http://passport.threeid.xyz/authenticate/github/callback"
INTERNAL_TWITTER_OAUTH_CALLBACK_URL = "https://passport.threeid.xyz/authenticate/twitter/callback"
INTERNAL_GOOGLE_ANALYTICS_TAG = "G-675VJMWSRY"

[env.current.build]
command = "yarn build"
