name = "access"
main = "src/index.ts"
compatibility_date = "2022-10-26"
node_compat = true
workers_dev = false

durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "EDGES", service = "edges" },
  { binding = "Starbase", service = "starbase" },
]

[dev]
port = 9393
local_protocol = "http"

[env.dev]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "EDGES", service = "edges-dev" },
  { binding = "Starbase", service = "starbase-dev" },
]

[env.next]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "EDGES", service = "edges-next" },
  { binding = "Starbase", service = "starbase-next" },
]

[env.current]
durable_objects.bindings = [
  { name = "Access", class_name = "Access" },
  { name = "Authorization", class_name = "Authorization" },
]
services = [
  { binding = "EDGES", service = "edges-current" },
  { binding = "Starbase", service = "starbase-current" },
]

[[migrations]]
tag = "v0"
new_classes = ["Access", "Authorization"]
