---
name: Galaxy

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./platform

jobs:
  build-publish-test-galaxy-dev:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build platform.nix

      - name: Install
        run: yarn workspaces focus -A

      - name: Code Generation
        run: yarn gql

      - name: Test
        run: yarn workspaces foreach -i -v -t --include galaxy run test

      - name: Deploy Galaxy to Dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          workingDirectory: 'platform/galaxy'
          command: publish --env dev
          environment: 'dev'
          secrets: |
            DATADOG_CLIENT_TOKEN
            DATADOG_APPLICATION_ID
            DATADOG_ENV
            DATADOG_SERVICE_NAME
            NFTAR_URL
            NFTAR_AUTHORIZATION
        env:
          SESSION_SECRET: 'secret'
          DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          DATADOG_APPLICATION_ID: ${{ secrets.DATADOG_APPLICATION_ID }}
          DATADOG_ENV: development
          DATADOG_SERVICE_NAME: 3id-application
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          NFTAR_URL: ${{ secrets.NFTAR_TEST_URL }}
          NFTAR_AUTHORIZATION: ${{ secrets.NFTAR_TEST_AUTHORIZATION }}
          MINTPFP_CONTRACT_ADDRESS: ${{ secrets.MINT_PFP_TEST_CONTRACT_ADDRESS }}
