# .github/workflows/main-edges.yaml
---
name: Edges

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./platform

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build platform.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Deploy edges D1 Database
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '2.6.2'
          workingDirectory: 'platform/edges'
          command: d1 migrations apply edges-dev --env dev
          environment: 'dev'

      - name: Deploy edges dev Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: '2.6.2'
          workingDirectory: 'platform/edges'
          command: publish --env dev
          environment: 'dev'
        env:
          NODE_ENV: 'development'
