# .github/workflows/next-console.yaml
---
name: Next Console

on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-test-console-next:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Test
        run: yarn workspaces foreach -i -v -t --include console run test

      - name: Deploy to Next Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/console'
          command: publish --env next
          environment: 'next'
          secrets: |
            SECRET_SESSION_KEY
        env:
          # A secret used for session encryption.
          SECRET_SESSION_KEY: ${{ secrets.SECRET_SESSION_KEY_TEST }}
