# .github/workflows/release-edges.yaml
---
name: Release Edges

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./platform

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build platform.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

        # NB: we do *not* drop and recreate the database. If applying
        # the SQL fails we'll need to migrate the database manually using:
        # $ wrangler d1 migrations

      - name: Deploy edges D1 Database
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'platform/edges'
          command: d1 migrations apply edges-current --env current
          environment: 'current'

      - name: Deploy edges current Worker
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'platform/edges'
          command: publish --env current
          environment: 'current'
