---
name: Release Profile
on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./apps

jobs:
  build-publish-profile-current:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-build apps.nix

      - name: Cache Dependencies
        id: cache-modules
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .yarn
          key: ${{ runner.os }}-node_modules-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install Dependencies
        run: yarn install

      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.TOKEN_CLOUDFLARE_API }}
          accountId: ${{ secrets.INTERNAL_CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: 'apps/profile'
          command: publish --env current
          environment: 'current'
          secrets: |
            SECRET_SESSION_SALT
            TOKEN_NFTAR
            CONSOLE_CLIENT_ID
            CONSOLE_CLIENT_SECRET
        env:
          SECRET_SESSION_SALT: ${{ secrets.SECRET_SESSION_SALT_PROD }}
          TOKEN_NFTAR: ${{ secrets.TOKEN_NFTAR_PROD }}
          CONSOLE_CLIENT_ID: ${{ secrets.INTERNAL_CONSOLE_OAUTH_CLIENT_ID_CURRENT }}
          CONSOLE_CLIENT_SECRET: ${{ secrets.SECRET_CONSOLE_OAUTH_CLIENT_SECRET_CURRENT }}
