# .github/workflows/release.yaml
---
name: release
on:
  push:
    tags:
      - "*"

jobs:

  # build
  # ----------------------------------------------------------------------------

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@master
      - uses: DeLaGuardo/setup-clojure@8.0
        with:
          bb: 0.8.156
          cli: 1.11.1.1149
      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - run: npm ci
      # - run: npm install cypress --save-dev
      - run: npm run test:all:release

  # three-id
  # ----------------------------------------------------------------------------

  three-id:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '18'

      - uses: DeLaGuardo/setup-clojure@8.0
        with:
          bb: 0.8.156
          cli: 1.11.1.1149

      - uses: actions/setup-node@v3
        with:
          node-version: lts/gallium
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: install node dependencies
        run: npm ci

      - name: build sdk-web
        run: npm run build:sdk-web:release

      - name: set tag as RELEASE_VERSION environment variable
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: install node dependencies (for three-id)
        working-directory: ./three-id
        run: npm ci

      - name: build and deploy three-id
        working-directory: ./three-id
        env:
          # These values are injected into the generated wrangler.toml.
          ADMIN_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          CURRENT_KV_APP_ID: ${{ secrets.CURRENT_KV_APP_ID }}
          CURRENT_URL: ${{ secrets.CURRENT_URL }}
          NEXT_KV_APP_ID: ${{ secrets.NEXT_KV_APP_ID }}
          NEXT_URL: ${{ secrets.NEXT_URL }}
          # The Datadog client token.
          DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          # The Cloudflare API token used by wrangler.
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bb deploy:app --deploy-env current --app-version ${{ env.RELEASE_VERSION }}

      - name: run smoke tests
        working-directory: ./three-id
        env:
          # These values are injected into the generated wrangler.toml.
          ADMIN_ACCOUNT_ID: ${{ secrets.ADMIN_ACCOUNT_ID }}
          CURRENT_KV_APP_ID: ${{ secrets.CURRENT_KV_APP_ID }}
          CURRENT_URL: ${{ secrets.CURRENT_URL }}
          NEXT_KV_APP_ID: ${{ secrets.NEXT_KV_APP_ID }}
          NEXT_URL: ${{ secrets.NEXT_URL }}
          # The Datadog client token.
          DATADOG_CLIENT_TOKEN: ${{ secrets.DATADOG_CLIENT_TOKEN }}
          # The Cloudflare API token used by wrangler.
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        run: bb test:smoke --deploy-env current
